fn main() {
    windows::build!(
        Windows::Win32::KeyboardAndMouseInput::{
            GetAsyncKeyState,
            GetKeyboardLayout,
        },
        Windows::Win32::SystemServices::{
            PWSTR,
            OpenProcess,
            PROCESS_ACCESS_RIGHTS,
            GetConsoleWindow,
        },
        Windows::Win32::ProcessStatus::{
            K32GetProcessImageFileNameW,
        },
        Windows::Win32::WindowsAndMessaging::{
            HWND,
            GetWindowTextLengthW,
            GetWindowTextW,
            GetWindowThreadProcessId,
            GetForegroundWindow,
            ShowWindow,
            SHOW_WINDOW_CMD,
        },
        Windows::Win32::WindowsProgramming::{
            CloseHandle,
        },
        Windows::Win32::IpHelper::{
            GetAdaptersInfo,
            IP_ADAPTER_INFO,
        },
    );
}
