[package]
name = "seguridad_keylogger"
version = "0.1.0"
authors = ["Raigiku <raigiku@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.7.0"
chrono = "0.4"

[build-dependencies]
windows = "0.7"